plugins {
    id 'com.android.application'
}

def keystorePath = System.getenv('KEYSTORE_PATH')

android {
    namespace 'com.kapp.tv'
    compileSdk 34

    defaultConfig {
        applicationId "com.kapp.tv"
        minSdk 21
        targetSdk 34
        versionCode 2
        versionName "1.0.1"
    }

    signingConfigs {
        release {
            if (keystorePath) {
                storeFile file(keystorePath)
                storePassword System.getenv('KEYSTORE_PASSWORD')
                keyAlias System.getenv('KEY_ALIAS')
                keyPassword System.getenv('KEY_PASSWORD')
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig keystorePath ? signingConfigs.release : signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
}
